name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [nightly]

    steps:
      - name: Set up a Rust toolchain
        uses: hecrj/setup-rust-action@v2.0.1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: cargo test --verbose
