name: Run Tests in changed file

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Check if any files have changed
      - name: Get changed files
        id: changed-rust-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            **.rs

      - name: List all changed files
        if: steps.changed-rust-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-rust-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      # Run tests only if files have changed, or return true if no changes
      - name: Run tests if changes found
        if: steps.changed-rust-files.outputs.any_changed == 'true'
        run: |
          cargo test
