name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get edited files
        id: edited_files
        run: |
          git diff-tree --no-commit-id --name-only ${{github.sha}} -r > edited_files.txt
        
      - name: Run tests for edited files
        run: |
          xargs -I {} cargo test --verbose --manifest-path={}
        shell: bash
        env:
          FILE_PATHS: ${{ steps.edited_files.outputs.stdout }}
