name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Filter Changed Files
      id: filter
      run: echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.rs$' || true)"
    - name: Build and Test
      if: steps.filter.outputs.changed_files != ''
      run: |
        echo "Changed Rust files: ${{ steps.filter.outputs.changed_files }}"
        cargo build --verbose
        cargo test --verbose
