name: Run Tests

on: [pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo test
        run: |
          cargo test
