name: Run Tests in changed file

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Check if any files have changed
      - name: Check for changed files
        id: check_files
        run: echo ::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

      # Run tests only if files have changed, or return true if no changes
      - name: Run tests if changes found
        if: ${{ steps.check_files.outputs.changed != '' || github.event_name == 'pull_request' }}
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changed files found: $CHANGED_FILES"
            # Add your test command here
          else
            echo "No changed files found."
            # Return true if no changes
            exit 0
          fi
